version: '3.1'

services:
  be_179934:
    image: kuzynihagrida1/prestashop:latest
    environment:
      DB_SERVER: actina15.maas
      DB_USER: kuzynihagrida
      DB_PASSWD: kuzynihagrida
      DB_NAME: kuzynihagrida
      PS_DOMAIN: localhost
      PS_FOLDER_ADMIN: admin959zyirsstq62mddx3e
      PS_INSTALL_AUTO: 0
      ADMIN_MAIL: kuzynihagrida@gmail.com
      ADMIN_PASSWD: Kuzyn1!2@
    ports:
      - 17993:80  # http
      - 17994:443 # https
    volumes: 
      - kuzynihagrida-prestashop-volume:/var/www/html
    networks:
      - admin_mysql

volumes:
  kuzynihagrida-prestashop-volume:

networks:
  admin_mysql:
    external:
      name: admin-mysql_default