<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8zmea8y\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8zmea8y/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container8zmea8y.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container8zmea8y\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container8zmea8y\appAppKernelProdContainer([
    'container.build_hash' => '8zmea8y',
    'container.build_id' => 'cc097777',
    'container.build_time' => 1669302593,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8zmea8y');
