<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0aE8Ive\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0aE8Ive/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container0aE8Ive.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container0aE8Ive\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container0aE8Ive\appAppKernelProdContainer([
    'container.build_hash' => '0aE8Ive',
    'container.build_id' => '19c66165',
    'container.build_time' => 1670606550,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0aE8Ive');
