<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2r5HjH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2r5HjH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerX2r5HjH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerX2r5HjH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerX2r5HjH\appAppKernelProdContainer([
    'container.build_hash' => 'X2r5HjH',
    'container.build_id' => 'f7235e92',
    'container.build_time' => 1670633050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2r5HjH');
